const AUTH_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  AUTH_ACTION_FAILED: 'AUTH_ACTION_FAILED',
  GET_USER_INFO: 'GET_USER_INFO',
  LOGOUT: 'LOGOUT'
}

export {
  AUTH_ACTIONS
};
