<<<<<<< HEAD
const AUTH_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  GET_USER_INFO: 'GET_USER_INFO',
  LOGOUT: 'LOGOUT'
}

export {
  AUTH_ACTIONS
=======
const LOGIN = 'LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';

export {
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAILED
>>>>>>> da2057495115a65039ffad4565e48fa98956a56a
};
