const AUTH_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  AUTH_ACTION_FAILED: 'AUTH_ACTION_FAILED',
  GET_USER_INFO: 'GET_USER_INFO',
  LOGOUT: 'LOGOUT'
}

const COURSES_ACTIONS = {
  GET_COURSES_LIST: 'GET_COURSES_LIST',
  COURSES_RECEIVED: 'COURSES_RECEIVED',
  COURSES_ACTION_FAILED: 'COURSES_ACTION_FAILED'
}

export {
  AUTH_ACTIONS,
  COURSES_ACTIONS
};
